#spring.datasource.url=jdbc:mysql://al.zswk.xyz:3306/zgx949?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#spring.datasource.username=zgx949
#spring.datasource.password=zgx949
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#mybatis.mapper-locations=classpath:mapper/*.xml
#
#spring.thymeleaf.cache=false
server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/denglu_sp?serverTimezone=GMT%2B8
    url: jdbc:mysql://al.zswk.xyz:3306/zgx949?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: zgx949
    password: zgx949

#热部署生效
spring.devtools.restart.enabled: true


